DROP TABLE IF EXISTS PHONES;

CREATE TABLE IF NOT EXISTS PHONES (
  ID                 VARCHAR(20)  NOT NULL PRIMARY KEY,
  BRAND              VARCHAR(100) NOT NULL,
  MODEL              VARCHAR(100) NOT NULL,
  NETWORK_TECHNOLOGY VARCHAR(100),
  BANDS_2G           VARCHAR(100),
  BANDS_3G           VARCHAR(100),
  BANDS_4G           VARCHAR(100),
  NETWORK_SPEED      VARCHAR(100),
  GPRS               VARCHAR(100),
  EDGE               VARCHAR(100),
  ANNOUNCED          VARCHAR(100),
  STATUS             VARCHAR(100),
  DIMENSIONS         VARCHAR(100),
  WEIGHT             VARCHAR(100),
  SIM                VARCHAR(100),
  DISPLAY_TYPE       VARCHAR(100),
  DISPLAY_RESOLUTION VARCHAR(100),
  DISPLAY_SIZE       VARCHAR(100),
  OS                 VARCHAR(100),
  CPU                VARCHAR(100),
  CHIPSET            VARCHAR(100),
  GPU                VARCHAR(100),
  MEMORY_CARD        VARCHAR(100),
  INTERNAL_MEMORY    VARCHAR(100),
  RAM                VARCHAR(100),
  PRIMARY_CAMERA     VARCHAR(100),
  SECONDARY_CAMERA   VARCHAR(100),
  LOUD_SPEAKER       VARCHAR(100),
  AUDIO_JACK         VARCHAR(100),
  WLAN               VARCHAR(100),
  BLUETOOTH          VARCHAR(100),
  GPS                VARCHAR(100),
  NFC                VARCHAR(100),
  RADIO              VARCHAR(100),
  USB                VARCHAR(100),
  SENSORS            VARCHAR(100),
  BATTERY            VARCHAR(100),
  COLORS             VARCHAR(100),
  PRICE              VARCHAR(100) NOT NULL,
  IMAGE_URL          VARCHAR(100)
);
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('2', 'Acer', 'Iconia Talk S', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2', 'HSDPA 850 / 1900 / 2100',
        'LTE band 1(2100)| 3(1800)| 7(2600)| 8(900)| 20(800)', 'HSPA 42.2/11.5 Mbps  LTE Cat4 150/50 Mbps', 'Yes', 'Yes', '2016  August', 'Available. Released 2016  October',
        '191.7 x 101 x 9.4 mm (7.55 x 3.98 x 0.37 in)', '260', 'Dual SIM (Micro-SIM/Nano-SIM)', 'IPS LCD capacitive touchscreen  16M colors',
        '7.0 inches (~69.8% screen-to-body ratio)', '720 x 1280 pixels (~210 ppi pixel density)', 'AndroID 6.0 (Marshmallow)', 'Quad-core 1.3 GHz Cortex-A53', 'Mediatek MT8735',
        'Mali-T720MP2', 'microSD  up to 128 GB (dedicated slot)', '16/32 GB', '2 GB RAM', '13 MP| autofocus', '2 MP| 720p', 'Yes', 'Yes',
        'Wi-Fi 802.11 a/b/g/n| Wi-Fi Direct| hotspot', '4.0| A2DP', 'Yes with A-GPS GLONASS', NULL, 'FM radio', 'microUSB 2.0', 'Accelerometer| proximity',
        'Non-removable Li-Ion 3400 mAh battery (12.92 Wh)', 'Black', '170', 'http://cdn2.gsmarena.com/vv/bigpic/acer-iconia-talk-s.jpg');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('3', 'Acer', 'LiquID Z6 Plus', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA', 'LTE',
        'HSPA 42.2/5.76 Mbps  LTE Cat4 150/50 Mbps', 'Yes', 'Yes', '2016  August', 'Available. Released 2016  December', '153.8 x 75.6 x 8.5 mm (6.06 x 2.98 x 0.33 in)', '169',
        'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)', 'IPS LCD capacitive touchscreen  16M colors', '5.5 inches (~71.7% screen-to-body ratio)',
        '1080 x 1920 pixels (~401 ppi pixel density)', 'AndroID 6.0 (Marshmallow)', 'Octa-core 1.3 GHz Cortex-A53', 'Mediatek MT6753', 'Mali-T720MP3',
        'microSD  up to 256 GB (uses SIM 2 slot)', '32 GB', '3 GB RAM', '13 MP| autofocus| LED flash', '5 MP', 'Yes', 'Yes', 'Wi-Fi 802.11 b/g/n| Wi-Fi Direct| hotspot',
        '4.0| A2DP', 'Yes with A-GPS', NULL, 'FM radio', 'microUSB 2.0', 'Fingerprint (front-mounted)| accelerometer| proximity', 'Removable Li-Po 4080 mAh battery',
        'Black| White', '250', 'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-z6-plus.jpg');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('4', 'Acer', 'LiquID Z6', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA', 'LTE', 'HSPA  LTE', 'Yes', 'Yes',
        '2016  August', 'Available. Released 2016  December', '-', NULL, 'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)',
        'IPS LCD capacitive touchscreen  16M colors', '5.0 inches', '720 x 1280 pixels (~294 ppi pixel density)', 'AndroID 6.0 (Marshmallow)', 'Quad-core 1.25 GHz Cortex-A53',
        'Mediatek MT6737', 'Mali-T720MP2', 'microSD  up to 256 GB', '8 GB', '1 GB RAM', '8 MP| autofocus| LED flash', '2 MP', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes with A-GPS', NULL,
        'FM radio', 'microUSB 2.0', 'Accelerometer| proximity', 'Removable Li-Ion 2000 mAh battery', 'Black| White', '120',
        'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-z6.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('5', 'Acer', 'Iconia Tab 10 A3-A40', 'No cellular connectivity', 'N/A', NULL, NULL, NULL, 'No', 'No', '2016  April', 'Available. Released 2016  June',
        '259 x 167 x 8.9 mm (10.20 x 6.57 x 0.35 in)', NULL, 'No', 'IPS LCD capacitive touchscreen  16M colors', '10.1 inches (~68.4% screen-to-body ratio)',
        '1920 x 1200 pixels (~224 ppi pixel density)', 'AndroID 6.0 (Marshmallow)', 'Quad-core 1.3 GHz Cortex-A53', 'Mediatek MT8163A', 'Mali-T720 MP2',
        'microSD  up to 256 GB (dedicated slot)', '16/32/64 GB', '2 GB RAM', '5 MP', '2 MP', 'Yes with stereo speakers (4 speakers)', 'Yes',
        'Wi-Fi 802.11 a/b/g/n/ac| dual-band| hotspot', 'Yes', NULL, NULL, 'No', 'microUSB 2.0', 'Accelerometer', 'Non-removable Li-Ion battery', 'Black', '230',
        'http://cdn2.gsmarena.com/vv/bigpic/acer-iconia-tab-10-a3-a40.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('6', 'Acer', 'LiquID X2', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900', 'HSDPA 900 / 1900 / 2100 - Europe| Taiwan', 'LTE 800 / 1800 / 2100 / 2600 - Europe',
        'HSPA 42.2/5.76 Mbps  LTE Cat4 150/50 Mbps', 'Yes', 'Yes', '2015  April', 'Available. Released 2016  February', '153.3 x 78.8 x 8.5 mm (6.04 x 3.10 x 0.33 in)', '166',
        'Triple SIM (Micro-SIM)', 'IPS LCD capacitive touchscreen  16M colors', '5.5 inches (~69.0% screen-to-body ratio)', '720 x 1280 pixels (~267 ppi pixel density)',
        'AndroID 5.1 (Lollipop)', 'Octa-core 1.3 GHz Cortex-A53', 'Mediatek MT6753', 'Mali-T720MP4', 'microSD  up to 32 GB (dedicated slot)', '32 GB', '3 GB RAM',
        '13 MP| f/1.8| autofocus| LED flash|', '13 MP| f/1.8| autofocus| LED flash', 'Yes', 'Yes', 'Wi-Fi 802.11 b/g/n| hotspot', '4.0| A2DP| LE', 'Yes with A-GPS', NULL,
        'FM radio', 'microUSB 2.0', 'Accelerometer| proximity| compass', 'Removable Li-Po 4020 mAh battery', 'Black| Gold', '230',
        'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-x2-1.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('8', 'Acer', 'LiquID Zest Plus', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA', 'LTE', 'HSPA  LTE', 'Yes', 'Yes',
        '2016  April', 'Available. Released 2016  July', '154 x 77 x 10 mm (6.06 x 3.03 x 0.39 in)', NULL, 'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)',
        'IPS LCD capacitive touchscreen  16M colors', '5.5 inches (~70.3% screen-to-body ratio)', '720 x 1280 pixels (~267 ppi pixel density)', 'AndroID 6.0 (Marshmallow)',
        'Quad-core 1.3 GHz Cortex-A53', 'Mediatek MT6735', 'Mali-T720MP2', 'microSD (dedicated slot)', '16 GB', '2 GB RAM', '13 MP| phase detection/laser autofocus| LED flash',
        '5 MP', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes with A-GPS', NULL, 'FM radio', 'microUSB 2.0', 'Accelerometer| proximity| compass', 'Non-removable Li-Ion 5000 mAh battery',
        'Blue| White', '200', 'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-zest-plus-z628.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('9', 'Acer', 'LiquID Zest', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA 850 / 900 / 1900 / 2100', 'LTE',
        'HSPA  LTE Cat4 150/50 Mbps', 'Yes', 'Yes', '2016  February', 'Available. Released 2016  April', '145.7 x 71.2 x 8.4 mm (5.74 x 2.80 x 0.33 in)', '125',
        'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)', 'IPS LCD capacitive touchscreen  16M colors', '5.0 inches (~66.4% screen-to-body ratio)',
        '720 x 1280 pixels (~294 ppi pixel density)', 'AndroID 6.0 (Marshmallow)', 'Quad-core 1.3 GHz - Z525', 'Mediatek MT6580 - Z525', 'Mali-400MP2 - Z525',
        'microSD  up to 32 GB (dedicated slot)', '8 GB', '1 GB RAM', '8 MP| f/2.0| autofocus| LED flash', '5 MP', 'Yes', 'Yes', 'Yes', '4.0| A2DP', 'Yes with A-GPS', NULL,
        'FM radio', 'microUSB 2.0', 'Accelerometer| proximity| compass', 'Removable Li-Ion 2000 mAh battery', 'Black| White', '110',
        'http://cdn2.gsmarena.com/vv/bigpic/acer-zest.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('10', 'Acer', 'Predator 8', 'No cellular connectivity', 'N/A', NULL, NULL, NULL, 'No', 'No', '2015  September', 'Available. Released 2015  November',
        '217.9 x 127 x 8.6 mm (8.58 x 5.0 x 0.34 in)', '353.8', 'No', 'IPS LCD capacitive touchscreen  16M colors', '8.0 inches (~67.1% screen-to-body ratio)',
        '1920 x 1200 pixels (~283 ppi pixel density)', 'AndroID 5.0 (Lollipop)', 'Quad-core 1.6 GHz', 'Intel Atom x7-Z8700', NULL, 'microSD  up to 256 GB (dedicated slot)',
        '32/64 GB', '2 GB RAM', '5 MP', '2 MP', 'Yes with stereo speakers (4 speakers)', 'Yes', 'Wi-Fi 802.11 a/b/g/n', '4.0| A2DP| LE', NULL, NULL, 'No', 'microUSB 2.0', 'Yes',
        'Non-removable Li-Po 4420 mAh battery', 'Black/Silver', '350', 'http://cdn2.gsmarena.com/vv/bigpic/acer-predator-8.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('11', 'Acer', 'LiquID Jade Primo', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2', 'HSDPA 850 / 900 / 1900 / 2100 - Europe/ Taiwan',
        'LTE 800 / 1800 / 2100 / 2600 - Europe', 'HSPA 42.2/5.76 Mbps  LTE-A (2CA) Cat6 300/50 Mbps', 'Yes', 'Yes', '2015  September', 'Available. Released 2016  April',
        '156.5 x 75.9 x 8.4 mm (6.16 x 2.99 x 0.33 in)', '150', 'Dual SIM (Nano-SIM| dual stand-by)', 'AMOLED capacitive touchscreen  16M colors',
        '5.5 inches (~70.2% screen-to-body ratio)', '1080 x 1920 pixels (~401 ppi pixel density)', 'Microsoft Windows 10',
        'Hexa-core (4x1.4 GHz Cortex-A53 & 2x1.8 GHz Cortex-A57)', 'Qualcomm MSM8992 Snapdragon 808', 'Adreno 418', 'microSD  up to 256 GB (uses SIM 2 slot)', '32 GB', '3 GB RAM',
        '21 MP| f/2.2| autofocus| dual-LED flash|', '8 MP| f/2.2| 1080p@30fps', 'Yes', 'Yes', 'Wi-Fi 802.11 a/b/g/n/ac| dual-band| WiFi Direct| hotspot', '4.0| A2DP| LE| EDR',
        'Yes with A-GPS', NULL, 'FM radio', '3.1| Type-C 1.0 reversible connector', 'Accelerometer| gyro| proximity| compass', 'Non-removable Li-Po 2870 mAh battery', 'Black',
        '220', 'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-jade-primo-.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('12', 'Acer', 'LiquID Z330', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA', 'LTE', 'HSPA  LTE', 'Yes', 'Yes',
        '2015  September', 'Available. Released 2015  October', '136 x 66.5 x 9.6 mm (5.35 x 2.62 x 0.38 in)', '142',
        'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)', 'IPS LCD capacitive touchscreen  16M colors', '4.5 inches (~61.7% screen-to-body ratio)',
        '480 x 854 pixels (~218 ppi pixel density)', 'AndroID 5.1 (Lollipop)', 'Quad-core 1.1 GHz Cortex-A7', 'Qualcomm MSM8909 Snapdragon 210', 'Adreno 304',
        'microSD (dedicated slot)', '8 GB', '1 GB RAM', '5 MP| autofocus| LED flash', '5 MP', 'Yes', 'Yes', 'Yes', '4.0| A2DP', 'Yes with A-GPS', NULL, 'FM radio', 'microUSB 2.0',
        'Accelerometer| proximity', 'Removable Li-Ion 2000 mAh battery', 'Mystic Black| Pure White', '110', 'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-z320-z330.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('13', 'Acer', 'LiquID Z320', 'GSM / HSPA', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA', NULL, 'HSPA 42.2/5.76 Mbps', 'Yes', 'Yes',
        '2015  September', 'Available. Released 2015  November', '136 x 66.5 x 9.6 mm (5.35 x 2.62 x 0.38 in)', '142',
        'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)', 'IPS LCD capacitive touchscreen  16M colors', '4.5 inches (~61.7% screen-to-body ratio)',
        '480 x 854 pixels (~218 ppi pixel density)', 'AndroID 5.1 (Lollipop)', 'Quad-core 1.0 GHz Cortex-A7', 'Qualcomm MSM8909 Snapdragon 210', 'Adreno 304',
        'microSD (dedicated slot)', '8 GB', '1 GB RAM', '5 MP| autofocus| LED flash', '2 MP', 'Yes', 'Yes', 'Yes', '4.0| A2DP', 'Yes with A-GPS', NULL, 'FM radio', 'microUSB 2.0',
        'Accelerometer| proximity', 'Removable Li-Po 2000 mAh battery', 'Pure White', '90', 'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-z320-z330.jpg;;;;;');
INSERT INTO PHONES(ID, BRAND, MODEL, NETWORK_TECHNOLOGY, BANDS_2G, BANDS_3G, BANDS_4G, NETWORK_SPEED, GPRS, EDGE, ANNOUNCED, STATUS, DIMENSIONS, WEIGHT, SIM,
                   DISPLAY_TYPE, DISPLAY_RESOLUTION, DISPLAY_SIZE, OS, CPU, Chipset, GPU, MEMORY_CARD, INTERNAL_MEMORY, RAM, PRIMARY_CAMERA, SECONDARY_CAMERA, LOUD_SPEAKER,
                   AUDIO_JACK, WLAN, BLUETOOTH, GPS, NFC, RADIO, USB, SENSORS, BATTERY, COLORS, PRICE, IMAGE_URL)
VALUES ('15', 'Acer', 'LiquID Z630', 'GSM / HSPA / LTE', 'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM MODEL only)', 'HSDPA', 'LTE', 'HSPA  LTE', 'Yes', 'Yes',
        '2015  September', 'Available. Released 2015  September', '156.3 x 77.5 x 8.9 mm (6.15 x 3.05 x 0.35 in)', '165',
        'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)', 'IPS LCD capacitive touchscreen  16M colors', '5.5 inches (~68.8% screen-to-body ratio)',
        '720 x 1280 pixels (~267 ppi pixel density)', 'AndroID 5.1 (Lollipop)', 'Quad-core 1.3 GHz Cortex-A53', 'Mediatek MT6735', 'Mali-T720MP2', 'microSD (dedicated slot)',
        '8 GB', '1 GB RAM', '8 MP| autofocus| LED flash', '8 MP', 'Yes', 'Yes', 'Yes', '4.0| A2DP', 'Yes with A-GPS', NULL, 'FM radio', 'microUSB 2.0| USB On-The-Go',
        'Accelerometer| proximity| compass', 'Removable Li-Ion 4000 mAh battery', 'Black', '200', 'http://cdn2.gsmarena.com/vv/bigpic/acer-liquID-z630.jpg;;;;;');
