DROP TABLE IF EXISTS phone;

CREATE TABLE IF NOT EXISTS phone(
   id                 VARCHAR(20) NOT NULL PRIMARY KEY,
   brand              VARCHAR(100) NOT NULL,
   model              VARCHAR(100) NOT NULL,
   network_technology VARCHAR(100),
   bands_2G           VARCHAR(100),
   bands_3G           VARCHAR(100),
   bands_4G           VARCHAR(100),
   network_speed      VARCHAR(100),
   GPRS               VARCHAR(100),
   EDGE               VARCHAR(100),
   announced          VARCHAR(100),
   status             VARCHAR(100),
   dimentions         VARCHAR(100),
   weight_g           VARCHAR(100),
   weight_oz          VARCHAR(100),
   SIM                VARCHAR(100),
   display_type       VARCHAR(100),
   display_resolution VARCHAR(100),
   display_size       VARCHAR(100),
   OS                 VARCHAR(100),
   CPU                VARCHAR(100),
   Chipset            VARCHAR(100),
   GPU                VARCHAR(100),
   memory_card        VARCHAR(100),
   internal_memory    VARCHAR(100),
   RAM                VARCHAR(100),
   primary_camera     VARCHAR(100),
   secondary_camera   VARCHAR(100),
   loud_speaker       VARCHAR(100),
   audio_jack         VARCHAR(100),
   WLAN               VARCHAR(100),
   bluetooth          VARCHAR(100),
   GPS                VARCHAR(100),
   NFC                VARCHAR(100),
   radio              VARCHAR(100),
   USB                VARCHAR(100),
   sensors            VARCHAR(100),
   battery            VARCHAR(100),
   colors             VARCHAR(100),
   approx_price_EUR   VARCHAR(100) NOT NULL,
   img_url            VARCHAR(100)
);
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('2','Acer','Iconia Talk S','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2','HSDPA 850 / 1900 / 2100','LTE band 1(2100)| 3(1800)| 7(2600)| 8(900)| 20(800)','HSPA 42.2/11.5 Mbps  LTE Cat4 150/50 Mbps','Yes','Yes','2016  August','Available. Released 2016  October','191.7 x 101 x 9.4 mm (7.55 x 3.98 x 0.37 in)','260','9.17','Dual SIM (Micro-SIM/Nano-SIM)','IPS LCD capacitive touchscreen  16M colors','7.0 inches (~69.8% screen-to-body ratio)','720 x 1280 pixels (~210 ppi pixel density)','Android 6.0 (Marshmallow)','Quad-core 1.3 GHz Cortex-A53','Mediatek MT8735','Mali-T720MP2','microSD  up to 128 GB (dedicated slot)','16/32 GB','2 GB RAM','13 MP| autofocus','2 MP| 720p','Yes','Yes','Wi-Fi 802.11 a/b/g/n| Wi-Fi Direct| hotspot','4.0| A2DP','Yes with A-GPS GLONASS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity','Non-removable Li-Ion 3400 mAh battery (12.92 Wh)','Black','170','http://cdn2.gsmarena.com/vv/bigpic/acer-iconia-talk-s.jpg');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('3','Acer','Liquid Z6 Plus','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA','LTE','HSPA 42.2/5.76 Mbps  LTE Cat4 150/50 Mbps','Yes','Yes','2016  August','Available. Released 2016  December','153.8 x 75.6 x 8.5 mm (6.06 x 2.98 x 0.33 in)','169','5.96','Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','5.5 inches (~71.7% screen-to-body ratio)','1080 x 1920 pixels (~401 ppi pixel density)','Android 6.0 (Marshmallow)','Octa-core 1.3 GHz Cortex-A53','Mediatek MT6753','Mali-T720MP3','microSD  up to 256 GB (uses SIM 2 slot)','32 GB','3 GB RAM','13 MP| autofocus| LED flash','5 MP','Yes','Yes','Wi-Fi 802.11 b/g/n| Wi-Fi Direct| hotspot','4.0| A2DP','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Fingerprint (front-mounted)| accelerometer| proximity','Removable Li-Po 4080 mAh battery','Black| White','250','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z6-plus.jpg');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('4','Acer','Liquid Z6','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA','LTE','HSPA  LTE','Yes','Yes','2016  August','Available. Released 2016  December','-',NULL,NULL,'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','5.0 inches','720 x 1280 pixels (~294 ppi pixel density)','Android 6.0 (Marshmallow)','Quad-core 1.25 GHz Cortex-A53','Mediatek MT6737','Mali-T720MP2','microSD  up to 256 GB','8 GB','1 GB RAM','8 MP| autofocus| LED flash','2 MP','Yes','Yes','Yes','Yes','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity','Removable Li-Ion 2000 mAh battery','Black| White','120','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z6.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('5','Acer','Iconia Tab 10 A3-A40','No cellular connectivity','N/A',NULL,NULL,NULL,'No','No','2016  April','Available. Released 2016  June','259 x 167 x 8.9 mm (10.20 x 6.57 x 0.35 in)',NULL,NULL,'No','IPS LCD capacitive touchscreen  16M colors','10.1 inches (~68.4% screen-to-body ratio)','1920 x 1200 pixels (~224 ppi pixel density)','Android 6.0 (Marshmallow)','Quad-core 1.3 GHz Cortex-A53','Mediatek MT8163A','Mali-T720 MP2','microSD  up to 256 GB (dedicated slot)','16/32/64 GB','2 GB RAM','5 MP','2 MP','Yes with stereo speakers (4 speakers)','Yes','Wi-Fi 802.11 a/b/g/n/ac| dual-band| hotspot','Yes',NULL,NULL,'No','microUSB 2.0','Accelerometer','Non-removable Li-Ion battery','Black','230','http://cdn2.gsmarena.com/vv/bigpic/acer-iconia-tab-10-a3-a40.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('6','Acer','Liquid X2','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900','HSDPA 900 / 1900 / 2100 - Europe| Taiwan','LTE 800 / 1800 / 2100 / 2600 - Europe','HSPA 42.2/5.76 Mbps  LTE Cat4 150/50 Mbps','Yes','Yes','2015  April','Available. Released 2016  February','153.3 x 78.8 x 8.5 mm (6.04 x 3.10 x 0.33 in)','166','5.86','Triple SIM (Micro-SIM)','IPS LCD capacitive touchscreen  16M colors','5.5 inches (~69.0% screen-to-body ratio)','720 x 1280 pixels (~267 ppi pixel density)','Android 5.1 (Lollipop)','Octa-core 1.3 GHz Cortex-A53','Mediatek MT6753','Mali-T720MP4','microSD  up to 32 GB (dedicated slot)','32 GB','3 GB RAM','13 MP| f/1.8| autofocus| LED flash|','13 MP| f/1.8| autofocus| LED flash','Yes','Yes','Wi-Fi 802.11 b/g/n| hotspot','4.0| A2DP| LE','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity| compass','Removable Li-Po 4020 mAh battery','Black| Gold','230','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-x2-1.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('8','Acer','Liquid Zest Plus','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA','LTE','HSPA  LTE','Yes','Yes','2016  April','Available. Released 2016  July','154 x 77 x 10 mm (6.06 x 3.03 x 0.39 in)',NULL,NULL,'Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','5.5 inches (~70.3% screen-to-body ratio)','720 x 1280 pixels (~267 ppi pixel density)','Android 6.0 (Marshmallow)','Quad-core 1.3 GHz Cortex-A53','Mediatek MT6735','Mali-T720MP2','microSD (dedicated slot)','16 GB','2 GB RAM','13 MP| phase detection/laser autofocus| LED flash','5 MP','Yes','Yes','Yes','Yes','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity| compass','Non-removable Li-Ion 5000 mAh battery','Blue| White','200','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-zest-plus-z628.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('9','Acer','Liquid Zest','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA 850 / 900 / 1900 / 2100','LTE','HSPA  LTE Cat4 150/50 Mbps','Yes','Yes','2016  February','Available. Released 2016  April','145.7 x 71.2 x 8.4 mm (5.74 x 2.80 x 0.33 in)','125','4.41','Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','5.0 inches (~66.4% screen-to-body ratio)','720 x 1280 pixels (~294 ppi pixel density)','Android 6.0 (Marshmallow)','Quad-core 1.3 GHz - Z525','Mediatek MT6580 - Z525','Mali-400MP2 - Z525','microSD  up to 32 GB (dedicated slot)','8 GB','1 GB RAM','8 MP| f/2.0| autofocus| LED flash','5 MP','Yes','Yes','Yes','4.0| A2DP','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity| compass','Removable Li-Ion 2000 mAh battery','Black| White','110','http://cdn2.gsmarena.com/vv/bigpic/acer-zest.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('10','Acer','Predator 8','No cellular connectivity','N/A',NULL,NULL,NULL,'No','No','2015  September','Available. Released 2015  November','217.9 x 127 x 8.6 mm (8.58 x 5.0 x 0.34 in)','353.8','12.49','No','IPS LCD capacitive touchscreen  16M colors','8.0 inches (~67.1% screen-to-body ratio)','1920 x 1200 pixels (~283 ppi pixel density)','Android 5.0 (Lollipop)','Quad-core 1.6 GHz','Intel Atom x7-Z8700',NULL,'microSD  up to 256 GB (dedicated slot)','32/64 GB','2 GB RAM','5 MP','2 MP','Yes with stereo speakers (4 speakers)','Yes','Wi-Fi 802.11 a/b/g/n','4.0| A2DP| LE',NULL,NULL,'No','microUSB 2.0','Yes','Non-removable Li-Po 4420 mAh battery','Black/Silver','350','http://cdn2.gsmarena.com/vv/bigpic/acer-predator-8.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('11','Acer','Liquid Jade Primo','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2','HSDPA 850 / 900 / 1900 / 2100 - Europe/ Taiwan','LTE 800 / 1800 / 2100 / 2600 - Europe','HSPA 42.2/5.76 Mbps  LTE-A (2CA) Cat6 300/50 Mbps','Yes','Yes','2015  September','Available. Released 2016  April','156.5 x 75.9 x 8.4 mm (6.16 x 2.99 x 0.33 in)','150','5.29','Dual SIM (Nano-SIM| dual stand-by)','AMOLED capacitive touchscreen  16M colors','5.5 inches (~70.2% screen-to-body ratio)','1080 x 1920 pixels (~401 ppi pixel density)','Microsoft Windows 10','Hexa-core (4x1.4 GHz Cortex-A53 & 2x1.8 GHz Cortex-A57)','Qualcomm MSM8992 Snapdragon 808','Adreno 418','microSD  up to 256 GB (uses SIM 2 slot)','32 GB','3 GB RAM','21 MP| f/2.2| autofocus| dual-LED flash|','8 MP| f/2.2| 1080p@30fps','Yes','Yes','Wi-Fi 802.11 a/b/g/n/ac| dual-band| WiFi Direct| hotspot','4.0| A2DP| LE| EDR','Yes with A-GPS',NULL,'FM radio','3.1| Type-C 1.0 reversible connector','Accelerometer| gyro| proximity| compass','Non-removable Li-Po 2870 mAh battery','Black','220','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-jade-primo-.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('12','Acer','Liquid Z330','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA','LTE','HSPA  LTE','Yes','Yes','2015  September','Available. Released 2015  October','136 x 66.5 x 9.6 mm (5.35 x 2.62 x 0.38 in)','142','5.01','Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','4.5 inches (~61.7% screen-to-body ratio)','480 x 854 pixels (~218 ppi pixel density)','Android 5.1 (Lollipop)','Quad-core 1.1 GHz Cortex-A7','Qualcomm MSM8909 Snapdragon 210','Adreno 304','microSD (dedicated slot)','8 GB','1 GB RAM','5 MP| autofocus| LED flash','5 MP','Yes','Yes','Yes','4.0| A2DP','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity','Removable Li-Ion 2000 mAh battery','Mystic Black| Pure White','110','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z320-z330.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('13','Acer','Liquid Z320','GSM / HSPA','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA',NULL,'HSPA 42.2/5.76 Mbps','Yes','Yes','2015  September','Available. Released 2015  November','136 x 66.5 x 9.6 mm (5.35 x 2.62 x 0.38 in)','142','5.01','Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','4.5 inches (~61.7% screen-to-body ratio)','480 x 854 pixels (~218 ppi pixel density)','Android 5.1 (Lollipop)','Quad-core 1.0 GHz Cortex-A7','Qualcomm MSM8909 Snapdragon 210','Adreno 304','microSD (dedicated slot)','8 GB','1 GB RAM','5 MP| autofocus| LED flash','2 MP','Yes','Yes','Yes','4.0| A2DP','Yes with A-GPS',NULL,'FM radio','microUSB 2.0','Accelerometer| proximity','Removable Li-Po 2000 mAh battery','Pure White','90','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z320-z330.jpg;;;;;');
INSERT INTO phone(id,brand,model,network_technology,bands_2G,bands_3G,bands_4G,network_speed,GPRS,EDGE,announced,status,dimentions,weight_g,weight_oz,SIM,display_type,display_resolution,display_size,OS,CPU,Chipset,GPU,memory_card,internal_memory,RAM,primary_camera,secondary_camera,loud_speaker,audio_jack,WLAN,bluetooth,GPS,NFC,radio,USB,sensors,battery,colors,approx_price_EUR,img_url) VALUES ('15','Acer','Liquid Z630','GSM / HSPA / LTE','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)','HSDPA','LTE','HSPA  LTE','Yes','Yes','2015  September','Available. Released 2015  September','156.3 x 77.5 x 8.9 mm (6.15 x 3.05 x 0.35 in)','165','5.82','Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)','IPS LCD capacitive touchscreen  16M colors','5.5 inches (~68.8% screen-to-body ratio)','720 x 1280 pixels (~267 ppi pixel density)','Android 5.1 (Lollipop)','Quad-core 1.3 GHz Cortex-A53','Mediatek MT6735','Mali-T720MP2','microSD (dedicated slot)','8 GB','1 GB RAM','8 MP| autofocus| LED flash','8 MP','Yes','Yes','Yes','4.0| A2DP','Yes with A-GPS',NULL,'FM radio','microUSB 2.0| USB On-The-Go','Accelerometer| proximity| compass','Removable Li-Ion 4000 mAh battery','Black','200','http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z630.jpg;;;;;');
